name: Test

on: ['push', 'pull_request']

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest
    container: node:lts

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: docker
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Jest
        run: yarn test
