name: Test

on: ['push', 'pull_request']

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest
    container: node:lts

    services:
      database:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: umbriel
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
        - 6379:6379
        options: >-
          --entrypoint redis-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Jest
        run: yarn test
        env:
          DATABASE_NAME: umbriel
          DATABASE_USER: postgres
          DATABASE_PASS: docker
          DATABASE_PORT: 5432
          DATABASE_HOST: database
          REDIS_HOST: redis
